// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgcwxvokcgjcobglebym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnY3d4dm9rY2dqY29iZ2xlYnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Nzc0MzMsImV4cCI6MjA1OTM1MzQzM30.a0L87iyE80Dyr2pjEBH-wrRE1_0cvBFjxolou7Ho5Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);